# Generated by Django 4.1.5 on 2023-04-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_name', models.CharField(default='', max_length=100)),
                ('assign_desc', models.TextField(blank=True)),
                ('assign_file', models.FileField(upload_to='assignments/')),
                ('assign_deadline', models.DateField()),
                ('assign_marks', models.FloatField(default='0', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(default='', max_length=100)),
                ('class_desc', models.TextField(blank=True)),
                ('class_code', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='', max_length=100)),
                ('course_code', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DepartProgramme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prog_name', models.CharField(default='', max_length=100)),
                ('offers_in', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Morning & Evening', 'Morning & Evening')], default='', max_length=50)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fac_id', models.AutoField(primary_key=True, serialize=False)),
                ('fac_name', models.CharField(default='', max_length=100)),
                ('fac_img', models.ImageField(default='', upload_to='faculty/')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_email', models.CharField(default='', max_length=100)),
                ('user_password', models.CharField(default='', max_length=100)),
                ('user_type', models.CharField(choices=[('HOD', 'HOD'), ('Student', 'Student'), ('Teacher', 'Teacher')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(default='', max_length=100)),
                ('quiz_desc', models.TextField(blank=True)),
                ('quiz_file', models.FileField(upload_to='quizzes/')),
                ('quiz_deadline', models.DateField()),
                ('quiz_marks', models.FloatField(default='0', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(default='', max_length=100)),
                ('student_enroll_no', models.CharField(default=0, max_length=100)),
                ('student_batch', models.IntegerField(default=0)),
                ('student_time_shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=50)),
                ('student_contact', models.IntegerField(default=0)),
                ('student_img', models.ImageField(default='', upload_to='students/')),
                ('student_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department')),
                ('student_depart_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.departprogramme')),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.loginuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_user', to='main_app.loginuser')),
            ],
        ),
        migrations.CreateModel(
            name='TotalBatche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.IntegerField(default=0)),
                ('time_shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=50)),
                ('depart_programme', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.departprogramme')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentJoinedClassroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_code', models.CharField(default=0, max_length=50)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(default='', max_length=100)),
                ('student_enroll_no', models.CharField(default='', max_length=100)),
                ('student_depart', models.CharField(default='', max_length=100)),
                ('student_enrolled_programme', models.CharField(default='', max_length=100)),
                ('student_batch', models.IntegerField(default=0)),
                ('student_time_shift', models.CharField(default='', max_length=20)),
                ('student_img', models.ImageField(default='', upload_to='students_attendance/')),
                ('attendance_week', models.IntegerField(default=0)),
                ('attendance_date', models.DateField()),
                ('attendance_status', models.CharField(default='', max_length=5)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
                ('fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_name', models.TextField(blank=True)),
                ('quiz_file', models.FileField(upload_to='submissions/quiz/')),
                ('quiz_total_marks', models.FloatField(default=0, max_length=100)),
                ('quiz_marks_obtained', models.FloatField(default=0, max_length=100)),
                ('status', models.CharField(default='Quiz Due', max_length=50)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('quiz_submission_date', models.DateField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classroom')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Lecutre',
            fields=[
                ('lec_id', models.AutoField(primary_key=True, serialize=False)),
                ('lec_name', models.CharField(default='', max_length=100)),
                ('lec_desc', models.TextField(blank=True)),
                ('lec_file', models.FileField(upload_to='lectures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('hod_id', models.AutoField(primary_key=True, serialize=False)),
                ('hod_name', models.CharField(default='', max_length=100)),
                ('hod_img', models.ImageField(default='', upload_to='hod/')),
                ('dep_name', models.CharField(default='', max_length=100)),
                ('hod_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.loginuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_user', to='main_app.loginuser')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyJobDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_type', models.CharField(choices=[('Permanent', 'Permanenet'), ('Vsiting', 'Vsiting')], default='', max_length=50)),
                ('time_shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Morning & Evening', 'Morning & Evening')], default='', max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='fac_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.loginuser'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main_app.loginuser'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hod'),
        ),
        migrations.AddField(
            model_name='course',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='fac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.faculty'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.loginuser'),
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('assign_name', models.CharField(default='', max_length=100)),
                ('assign_file', models.FileField(upload_to='submissions/assignments/')),
                ('assign_total_marks', models.FloatField(default=0, max_length=100)),
                ('assign_marks_obtained', models.FloatField(default=0, max_length=100)),
                ('status', models.CharField(default='Quiz Due', max_length=50)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('assignment_submission_date', models.DateField(default='2022-04-05')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.assignment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classroom'),
        ),
        migrations.CreateModel(
            name='AssignCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.IntegerField(default=0)),
                ('time_shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=50)),
                ('active', models.BooleanField(default=True, max_length=50)),
                ('assign_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.department')),
                ('depart_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.departprogramme')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('ann_id', models.AutoField(primary_key=True, serialize=False)),
                ('ann_name', models.CharField(default='', max_length=100)),
                ('ann_desc', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classroom')),
            ],
        ),
    ]
