# Generated by Django 4.1.5 on 2023-04-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegisterCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_shft', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=20)),
                ('batch_year', models.IntegerField(default=0)),
                ('semester', models.CharField(choices=[('Semester 01', 'Semester01'), ('Semester 02', 'Semester02'), ('Semester 03', 'Semester03'), ('Semester 04', 'Semester04'), ('Semester 05', 'Semester05'), ('Semester 06', 'Semester06'), ('Semester 07', 'Semester07'), ('Semester 08', 'Semester08')], default='', max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.totalbatche')),
                ('courses', models.ManyToManyField(to='main_app.course')),
                ('depart_programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.departprogramme')),
            ],
        ),
    ]
