# Generated by Django 4.1.5 on 2023-04-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_studentregistercourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistercourse',
            old_name='time_shft',
            new_name='time_shift',
        ),
    ]
