# Generated by Django 4.1.5 on 2023-04-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_studentregistercourse_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_clos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clos', models.CharField(default='', max_length=50)),
                ('clos_objective', models.CharField(default='', max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
                ('fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.faculty')),
            ],
        ),
    ]
