# Generated by Django 4.1.5 on 2023-04-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_add_clos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_clos',
            new_name='AddClo',
        ),
    ]
