# Generated by Django 4.1.5 on 2023-04-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_add_clos_addclo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddClo',
            new_name='AddCourseClo',
        ),
    ]
