# Generated by Django 4.1.5 on 2023-04-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_addclo_addcourseclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcourseclo',
            name='total_clos',
            field=models.CharField(default='', max_length=50),
        ),
    ]
