# Generated by Django 4.1.5 on 2023-04-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_addcourseclo_total_clos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourseclo',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
    ]
