# Generated by Django 4.1.5 on 2023-04-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_addcourseclo_clos_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcourseclo',
            name='clos_objective',
            field=models.CharField(default='', max_length=200),
        ),
    ]
