# Generated by Django 4.1.5 on 2023-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_addassessmentclosplo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addassessmentclosplo',
            name='questions',
        ),
        migrations.AddField(
            model_name='addassessmentclosplo',
            name='total_questions',
            field=models.CharField(default='', max_length=50),
        ),
    ]
