# Generated by Django 4.1.5 on 2023-04-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_addassessmentclosplo_questions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addassessmentclosplo',
            old_name='assessment_number',
            new_name='assessment_name',
        ),
    ]
