# Generated by Django 4.1.5 on 2023-04-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_uploadresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadresult',
            name='student_enroll_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadresult',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
