# Generated by Django 4.1.5 on 2023-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_uploadresult_student_enroll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addassessmentclosplo',
            name='total_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadresult',
            name='obtained_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadresult',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
