# Generated by Django 4.1.5 on 2023-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_addassessmentclosplo_total_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addassessmentclosplo',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
