# Generated by Django 4.1.5 on 2023-04-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_addassessmentclosplo_total_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadresult',
            old_name='total_plos_clos_cover',
            new_name='mapped_plos_clos_cover',
        ),
    ]
