# Generated by Django 4.1.5 on 2023-04-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_rename_total_plos_clos_cover_uploadresult_mapped_plos_clos_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addassessmentclosplo',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadresult',
            name='obtained_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadresult',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
    ]
