# Generated by Django 4.2.1 on 2023-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_addassessmentclosplo_total_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='user_type',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('HOD & Teacher', 'HOD & Teacher')], default='', max_length=20),
        ),
    ]
