# Generated by Django 4.2.1 on 2023-11-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_loginuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addassessmentclosplo',
            name='question_wise_map_clos_plos',
            field=models.CharField(default='', max_length=255),
        ),
    ]
