# Generated by Django 4.2.1 on 2023-12-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_course_credit_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('lecture', 'Lecture'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('announcement', 'Announcement')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
    ]
