# Generated by Django 4.2.1 on 2023-12-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_pushnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotification',
            old_name='classroom_id',
            new_name='classroom',
        ),
    ]
