# Generated by Django 4.2.1 on 2023-12-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_rename_classroom_id_pushnotification_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plo', models.PositiveIntegerField(default='')),
                ('plo_desc', models.CharField(default='', max_length=255)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.departprogramme')),
            ],
        ),
    ]
