# Generated by Django 4.2.1 on 2023-12-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_plo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plo',
            name='plo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
