# Generated by Django 4.2.1 on 2023-12-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_alter_plo_plo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plo',
            name='plo_num',
            field=models.CharField(default='', max_length=100),
        ),
    ]
